/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazSwing;

import dominio.UsuarioAdministrador;
import observer.Observable;
import observer.Observable.Evento;
import servicios.Fachada;
import observer.Observer;

/**
 *
 * @author Julio Cesar
 */
public class VentanaUsuariosConectados extends javax.swing.JDialog implements Observer {

    /**
     * Creates new form VentanaUsuarioConectados
     */
    public VentanaUsuariosConectados(java.awt.Frame parent, boolean modal, UsuarioAdministrador usuario) {
        super(parent, modal);
        initComponents();
        setTitle("Bienvenido Admin");

        Fachada.getInstancia().suscribir(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lSesiones = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setViewportView(lSesiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void actualizar() {
        lSesiones.setListData(Fachada.getInstancia().getSesionesActivas().toArray());
    }

    @Override
    public void notificar(Observable origen, Evento event) {
        Observable.Evento e = (Observable.Evento) event;
        if (e.equals(Observable.Evento.LISTA_SESIONES_ACTUALIZADA)) {
            this.actualizar();
        }
    }

    private void cerrar() {
        Fachada.getInstancia().desuscribir(this);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lSesiones;
    // End of variables declaration//GEN-END:variables

}
