/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazSwing;

import dominio.Contacto;
import dominio.Telefono;
import dominio.TipoContacto;
import dominio.TipoTelefono;
import dominio.UsuarioAgenda;
import exception.AgendaException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import observer.Observable;
import observer.Observer;
import servicios.Fachada;

/**
 *
 * @author Julio Cesar
 */
public class VentanaAgenda extends javax.swing.JDialog implements Observer {

    private UsuarioAgenda usuario;

    public VentanaAgenda(java.awt.Frame parent, boolean modal, UsuarioAgenda user) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        usuario = user;
        //TODO: implementar renderes para comboBoxs
        cargarInformacionDelUsuarioEnAgenda();
        this.usuario.getAgenda().suscribir(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cTiposContactos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        inputNumero = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        btnCrearContacto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaContactos = new javax.swing.JList();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detallesContacto = new javax.swing.JTextArea();
        cTiposTelefonos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Numero");

        jLabel3.setText("Tipo de Contacto");

        btnCrearContacto.setText("Crear contacto");
        btnCrearContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearContactoActionPerformed(evt);
            }
        });

        listaContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaContactosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listaContactos);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar contacto: ");

        detallesContacto.setColumns(20);
        detallesContacto.setRows(5);
        detallesContacto.setCaretColor(new java.awt.Color(70, 70, 70));
        detallesContacto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        detallesContacto.setEnabled(false);
        jScrollPane1.setViewportView(detallesContacto);
        detallesContacto.setEnabled(false);

        jLabel5.setText("Tipo de Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cTiposTelefonos, 0, 220, Short.MAX_VALUE)
                            .addComponent(cTiposContactos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrearContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(inputNumero)
                            .addComponent(inputNombre))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cTiposContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cTiposTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearContacto))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
        new IuEntrada();
    }//GEN-LAST:event_formWindowClosing

    private void btnCrearContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContactoActionPerformed
        this.crearContacto();
    }//GEN-LAST:event_btnCrearContactoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        listaContactos.setListData(buscarContactos(txtBuscar.getText()).toArray());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void listaContactosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaContactosMousePressed
        this.mostrarDetallesContacto();
    }//GEN-LAST:event_listaContactosMousePressed

    private void cerrar() {
        Fachada.getInstancia().cerrar(usuario);
    }

    private void cargarInformacionDelUsuarioEnAgenda() {
        inicializarComboTiposContactos();
        inicializarComboTiposTelefonos();
        inicializarInformacionUsuario();
        inicializarAgenda();
    }

    private void inicializarInformacionUsuario() {
        setTitle("Bienvenido a su agenda " + usuario.getNombre() + ", cantidad de contactos: " + usuario.getAgenda().getCantidadContactos());
    }

    private void inicializarComboTiposContactos() {
        ArrayList<TipoContacto> tiposContactos = Fachada.getInstancia().getTiposContactos();
        for (TipoContacto tc : tiposContactos) {
            cTiposContactos.addItem(tc);
        }

    }

    private void inicializarComboTiposTelefonos() {
        ArrayList<TipoTelefono> tiposTelefonos = Fachada.getInstancia().getTipoTelefonos();
        for (TipoTelefono tt : tiposTelefonos) {
            cTiposTelefonos.addItem(tt);
        }
    }

    private void inicializarAgenda() {
        ArrayList<Contacto> contactos = usuario.getAgenda().getContactos();
        ArrayList<String> StringContactos = new ArrayList<>();
        if (contactos.isEmpty()) {
            String msg = "No tiene contactos en la agenda";
            StringContactos.add(msg);
        } else {
            for (Contacto contacto : contactos) {
                StringContactos.add(contacto.getNombre());
            }
        }
        listaContactos.setListData(StringContactos.toArray());
    }

    private void crearContacto() {
        TipoContacto tc = (TipoContacto) cTiposContactos.getSelectedItem();
        String nombre = inputNombre.getText();
        Telefono telefono = new Telefono(inputNumero.getText(), (TipoTelefono) cTiposTelefonos.getSelectedItem());
        try {
            usuario.getAgenda().agregarContacto(tc, nombre, telefono);
            inicializarAgenda();
            inicializarInformacionUsuario();
            limpiarInputs();
        } catch (AgendaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    private ArrayList<String> buscarContactos(String cadena) {
        ArrayList<Contacto> contactos = usuario.getAgenda().obtenerContactos(cadena);
        ArrayList<String> cadenaContactos = new ArrayList<>();

        if (contactos.isEmpty()) {
            String msg = "No se encontro el contacto";
            cadenaContactos.add(msg);
            limpiarDetallesContacto();
        } else {
            for (Contacto c : contactos) {
                cadenaContactos.add(c.getNombre());
                limpiarDetallesContacto();
            }
        }
        return cadenaContactos;
    }

    private void mostrarDetallesContacto() {
        String nombreContacto = listaContactos.getSelectedValue().toString();
        Contacto contacto = usuario.getAgenda().contactoSeleccionado(nombreContacto);
        if (contacto != null) {
            detallesContacto.setText("Tipo contacto: " + contacto.getTipoContacto() + "\n"
                    + "Tipo de telefono: " + contacto.getTelefono().getTipoTelefono().getNombre() + "\n"
                    + "Nombre: " + contacto.getNombre() + "\n"
                    + "Telefono: " + contacto.getTelefono());
        } else {
            detallesContacto.setText("Nop");
        }
    }

    @Override
    public void notificar(Observable origen, Observable.Evento event) {
        Observable.Evento e = (Observable.Evento) event;
        if (e.equals(Observable.Evento.AGENDA_ACTUALIZADA)) {
            this.cargarInformacionDelUsuarioEnAgenda();
        }
    }

    private void limpiarDetallesContacto() {
        detallesContacto.setText("");
    }

    private void limpiarInputs() {
        inputNombre.setText("");
        inputNombre.requestFocus();
        inputNumero.setText("");
        cTiposContactos.setSelectedIndex(0);
        cTiposTelefonos.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearContacto;
    private javax.swing.JComboBox cTiposContactos;
    private javax.swing.JComboBox cTiposTelefonos;
    private javax.swing.JTextArea detallesContacto;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaContactos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
